### Bnagumi Search with air_date
POST https://api.bgm.tv/v0/search/subjects
Content-Type: application/json

{
    "type": [
        2
    ],
    "filter": {
        "air_date": [
            ">=2020-07-01",
            "<2020-08-01"
        ]
    }
}
